services:
  db:
    image: postgres:15-alpine
    container_name: casino_postgres
    restart: always
    environment:
      POSTGRES_USER: casino
      POSTGRES_PASSWORD: casino
      POSTGRES_DB: casino_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    networks:
      - casino-network

  backend:
    build: ./backend_intro_devops_casino
    container_name: casino_backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: casino
      DB_PASSWORD: casino
      DB_NAME: casino_db
    networks:
      - casino-network

  frontend:
    build: ./frontend_intro_devops_casino-develop
    container_name: casino_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - casino-network

# Red interna y volúmenes
networks:
  casino-network:
    driver: bridge

volumes:
  pgdata: